[package]
name = "pg_named_args"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/tandemdrive/pg_named_args"
description = "PostgreSQL named arguments"
license = "MIT OR Apache-2.0"

[dependencies]
